import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { type RouterOutputs, api } from "@/utils/api";
import { Button } from "@/components/ui/button";
import * as z from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import { CreatePostWizard } from "@/components/CreatePostWizard";
import { SiteHeader } from "@/components/SiteHeader";
import { Avatar, AvatarImage } from "@/components/ui/avatar";

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { author, post } = props;
  return (
    <Card>
      <CardHeader className="flex flex-row">
        <Avatar>
          <AvatarImage
            src={
              author?.imageUrl ??
              `https://api.dicebear.com/6.x/notionists-neutral/svg?seed=${user?.id}`
            }
          />
        </Avatar>
        <CardTitle className="px-4">{author?.firstName}</CardTitle>
      </CardHeader>
      <CardContent>
        <p>{post.content}</p>
      </CardContent>
    </Card>
  );
};

export default function Home() {
  const { data } = api.posts.getAll.useQuery();

  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SiteHeader />
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {!user.isSignedIn && (
            <SignInButton>
              <Button variant={"outline"}>Sign in with Clerk</Button>
            </SignInButton>
          )}
          {user.isSignedIn && (
            <SignOutButton>
              <Button variant={"outline"}>Sign out with Clerk</Button>
            </SignOutButton>
          )}

          {user.isSignedIn && <CreatePostWizard />}

          <div className="w-full max-w-2xl">
            {data?.map((fullPost) => {
              return <PostView key={fullPost.post.id} {...fullPost} />;
            })}
          </div>
        </div>
      </main>
    </>
  );
}
