import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { api } from "@/utils/api";
import { Button } from "@/components/ui/button";
import * as z from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { CreatePostWizard } from "@/components/createPostWizard";

export default function Home() {
  const { data } = api.posts.getAll.useQuery();

  const user = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {!user.isSignedIn && (
            <SignInButton>
              <Button variant={"outline"}>Sign in with Clerk</Button>
            </SignInButton>
          )}
          {user.isSignedIn && (
            <SignOutButton>
              <Button variant={"outline"}>Sign out with Clerk</Button>
            </SignOutButton>
          )}
          <div>
            {data?.map((post) => {
              return <div key={post.id}>{post.content}</div>;
            })}
          </div>
          {user.isSignedIn && <CreatePostWizard />}
        </div>
      </main>
    </>
  );
}
