import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";

import { type RouterOutputs, api } from "@/utils/api";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

import { CreatePost } from "@/components/CreatePost";
import { SiteHeader } from "@/components/SiteHeader";
import { Avatar, AvatarImage } from "@/components/ui/avatar";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { LoadingSpinner } from "@/components/LoadingSpinner";
import AppLayout from "@/components/AppLayout";
import Link from "next/link";

dayjs.extend(relativeTime);

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { author, post } = props;
  return (
    <Card>
      <CardHeader className="flex flex-row">
        <Avatar>
          <AvatarImage
            src={
              author?.imageUrl ??
              `https://api.dicebear.com/6.x/notionists-neutral/svg?seed=${author?.id}`
            }
          />
        </Avatar>
        <CardTitle className="px-4 text-sm text-slate-700">
          <span>{author?.firstName} · </span>
          <span className="">{dayjs(post.createdAt).fromNow()}</span>
        </CardTitle>
      </CardHeader>
      <CardContent>
        <p>{post.content}</p>
      </CardContent>
    </Card>
  );
};

export default function Home() {
  const { data, isLoading } = api.posts.getAll.useQuery();

  const user = useUser();

  if (isLoading) {
    // TODO: Add proper loading UI...
    return (
      <div className="flex h-screen w-screen items-center justify-center">
        <LoadingSpinner />
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Yeeter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppLayout>
          <div className="py-4">{user.isSignedIn && <CreatePost />}</div>

          {data?.map((fullPost) => {
            return (
              <Link key={fullPost.post.id} href={`/post/${fullPost.post?.id}`}>
                <div className="py-2">
                  <PostView {...fullPost} />
                </div>
              </Link>
            );
          })}
        </AppLayout>
      </main>
    </>
  );
}
